export { shapeDistance, shapeVertices, HALFTONE_SHAPE_IDS, type HalftoneShape } from './shapes';
export {
  glyphDistance,
  glyphSvg,
  glyphBand,
  assignGlyphs,
  parseGlyphRamp,
  resolveGlyphRamp,
  GLYPH_IDS,
  GLYPH_CODE,
  GLYPH_RAMPS,
  GLYPH_ALIASES,
  ACCENT_MIN_SIZE,
  type GlyphId,
  type GlyphRampKind,
  type GlyphAssignOptions,
} from './glyphs';
export { buildWarp, type WarpKind, type WarpSettings, type WarpField } from './warp';
export {
  buildHalftone,
  coverageToSize,
  gainedCoverage,
  gridTransform,
  cellCenter,
  dotOffset,
  baseRadius,
  lineHalfWidth,
  glyphHalfStroke,
  glyphSpan,
  countDots,
  DEFAULT_HALFTONE,
  CMYK_ANGLES,
  CMYK_INKS,
  CELL_SAMPLES,
  type HalftoneSettings,
  type HalftoneSource,
  type HalftoneScreen,
  type HalftoneGeometry,
  type LatticeKind,
  type InkMode,
  type SizeMapping,
  type GridTransform,
} from './geometry';
export { renderHalftone, smoothMin } from './render';
export { halftoneToSvg, MAX_SVG_DOTS } from './svg';
